#!/bin/sh
bspc rule -r "*"
###---MONITORS---###
bspc monitor -d 1 2 3 4 5 6 7 8 9

#run
#/home/alx/.scripts/lp.lua

polybar bar&
#tint2&
xsetroot -cursor_name left_ptr
#pgrep -x stalonetray > /dev/null || stalonetray &
#pgrep -x panel > /dev/null || ~/.config/lemonbar/panel &

###---Global Settings---###
#bspc config honor_size_hints true
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
bspc config focused_border_color	"#373737"

bspc config focus_follows_pointer false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config borderless_monocle   false
bspc config gapless_monocle      true
###---Monitor And Desktop Settings----###
bspc ignore_ewmh_struts
bspc config top_padding 23
#bspc config bottom_padding 0
#bspc config left_padding 0
#bspc config right_padding 0
bspc config border_width 1
bspc config window_gap 1

###---Rules---###
#bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a bookmarker state=floating
