#! /bin/sh

export PANEL_FIFO=/tmp/state-fifo
export PANEL_HEIGHT=23
export PANEL_FONT="JetBrainsMono Nerd Font Mono:style=Medium:size=8"
export PANEL_WM_NAME=bspwm_panel


trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc subscribe report > "$PANEL_FIFO" &
~/.config/polybar/panel_bar < "$PANEL_FIFO"


